export {default as Home} from './Home'
export {default as AddBlog} from './AddBlog'
export {default as Auth} from './Auth'
export {default as Settings} from './Settings'
export {default as About} from './About'
export {default as SingleBlog} from './SingleBlog'
export {default as UserProfile} from './UserProfile'
export {default as NotFoundPage} from './NotFoundPage'
